
CREATE SEQUENCE AssetSequence START WITH 1000 INCREMENT BY 1 NOCACHE  NOCYCLE;
CREATE SEQUENCE AttributeValueSequence START WITH 1000 INCREMENT BY 1 NOCACHE  NOCYCLE;
CREATE SEQUENCE AssetBoxSequence START WITH 1000 INCREMENT BY 1 NOCACHE  NOCYCLE;
CREATE SEQUENCE UsageTypeSequence START WITH 1000 INCREMENT BY 1 NOCACHE  NOCYCLE;
CREATE SEQUENCE UserSequence START WITH 1000 INCREMENT BY 1 NOCACHE  NOCYCLE;
CREATE SEQUENCE UserGroupSequence START WITH 1000 INCREMENT BY 1 NOCACHE  NOCYCLE;
CREATE SEQUENCE CategorySequence START WITH 1000 INCREMENT BY 1 NOCACHE  NOCYCLE;
CREATE SEQUENCE AttributeSequence START WITH 1000 INCREMENT BY 1 NOCACHE  NOCYCLE;
CREATE SEQUENCE ABOrderSequence START WITH 1000 INCREMENT BY 1 NOCACHE  NOCYCLE;
CREATE SEQUENCE OrgUnitSequence START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE UsageTypeFormatSequence START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE ChangeAttributeRuleSeq START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SendEmailDateRuleSequence START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE ListSequence START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE ListItemSequence START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE DivisionSequence START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE AddressSequence START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SubscriptionSequence START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SubscriptionModelSequence START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE PriceBandSequence START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE CategoryTypeSequence START WITH 1000 INCREMENT BY 1 NOCACHE  NOCYCLE;
CREATE SEQUENCE RoleSequence START WITH 1000 INCREMENT BY 1 NOCACHE  NOCYCLE;

CREATE SEQUENCE EmbeddedDataValueSequence START WITH 1000 INCREMENT BY 1 NOCACHE  NOCYCLE;
CREATE SEQUENCE EmbeddedDataTypeSequence START WITH 1000 INCREMENT BY 1 NOCACHE  NOCYCLE;
CREATE SEQUENCE MappingDirectionSequence START WITH 1000 INCREMENT BY 1 NOCACHE  NOCYCLE;

CREATE SEQUENCE EmailTemplateSequence START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE LanguageSequence START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE MarketingGroupSequence START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE MarketingEmailSequence START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;

