-- Reference data for the standard Asset bank --

-- You should update refdata-countries.sql, but DO NOT manually update refdata-countries-sqlserver.sql 
-- To generate refdata-countries-sqlserver.sql, run the ant target db-sqlserver-refdata-countries (replaces "-- SQLSERVER " with "").

-- SQLSERVER SET IDENTITY_INSERT Country ON;
INSERT INTO Country (Id, Name) VALUES (1,'Afghanistan');
INSERT INTO Country (Id, Name) VALUES (2,'Albania');
INSERT INTO Country (Id, Name) VALUES (3,'Algeria');
INSERT INTO Country (Id, Name) VALUES (4,'Andorra');
INSERT INTO Country (Id, Name) VALUES (5,'Angola');
INSERT INTO Country (Id, Name) VALUES (6,'Antigua and Barbuda');
INSERT INTO Country (Id, Name) VALUES (7,'Argentina');
INSERT INTO Country (Id, Name) VALUES (8,'Armenia');
INSERT INTO Country (Id, Name) VALUES (9,'Australia');
INSERT INTO Country (Id, Name) VALUES (10,'Austria');
INSERT INTO Country (Id, Name) VALUES (11,'Azerbaijan');
INSERT INTO Country (Id, Name) VALUES (12,'Bahamas');
INSERT INTO Country (Id, Name) VALUES (13,'Bahrain');
INSERT INTO Country (Id, Name) VALUES (14,'Bangladesh');
INSERT INTO Country (Id, Name) VALUES (15,'Barbados');
INSERT INTO Country (Id, Name) VALUES (16,'Belarus');
INSERT INTO Country (Id, Name) VALUES (17,'Belgium');
INSERT INTO Country (Id, Name) VALUES (18,'Belize');
INSERT INTO Country (Id, Name) VALUES (19,'Benin');
INSERT INTO Country (Id, Name) VALUES (20,'Bhutan');
INSERT INTO Country (Id, Name) VALUES (21,'Bolivia');
INSERT INTO Country (Id, Name) VALUES (22,'Bosnia and Herzegovina');
INSERT INTO Country (Id, Name) VALUES (23,'Botswana');
INSERT INTO Country (Id, Name) VALUES (24,'Brazil');
INSERT INTO Country (Id, Name) VALUES (25,'Brunei');
INSERT INTO Country (Id, Name) VALUES (26,'Bulgaria');
INSERT INTO Country (Id, Name) VALUES (27,'Burkina Faso');
INSERT INTO Country (Id, Name) VALUES (28,'Burundi');
INSERT INTO Country (Id, Name) VALUES (29,'Cambodia');
INSERT INTO Country (Id, Name) VALUES (30,'Cameroon');
INSERT INTO Country (Id, Name) VALUES (31,'Canada');
INSERT INTO Country (Id, Name) VALUES (32,'Cape Verde');
INSERT INTO Country (Id, Name) VALUES (33,'Central African Republic');
INSERT INTO Country (Id, Name) VALUES (34,'Chad');
INSERT INTO Country (Id, Name) VALUES (35,'Chile');
INSERT INTO Country (Id, Name) VALUES (36,'China');
INSERT INTO Country (Id, Name) VALUES (37,'Colombia');
INSERT INTO Country (Id, Name) VALUES (38,'Comoros');
INSERT INTO Country (Id, Name) VALUES (39,'Congo');
INSERT INTO Country (Id, Name) VALUES (40,'Congo, Democratic Republic of the');
INSERT INTO Country (Id, Name) VALUES (41,'Costa Rica');
INSERT INTO Country (Id, Name) VALUES (42,'Croatia');
INSERT INTO Country (Id, Name) VALUES (43,'Cuba');
INSERT INTO Country (Id, Name) VALUES (44,'Cyprus');
INSERT INTO Country (Id, Name) VALUES (45,'Czech Republic');
INSERT INTO Country (Id, Name) VALUES (46,'Cote d Ivoire');
INSERT INTO Country (Id, Name) VALUES (47,'Denmark');
INSERT INTO Country (Id, Name) VALUES (48,'Djibouti');
INSERT INTO Country (Id, Name) VALUES (49,'Dominica');
INSERT INTO Country (Id, Name) VALUES (50,'Dominican Republic');
INSERT INTO Country (Id, Name) VALUES (51,'East Timor');
INSERT INTO Country (Id, Name) VALUES (52,'Ecuador');
INSERT INTO Country (Id, Name) VALUES (53,'Egypt');
INSERT INTO Country (Id, Name) VALUES (54,'El Salvador');
INSERT INTO Country (Id, Name) VALUES (55,'Equatorial Guinea');
INSERT INTO Country (Id, Name) VALUES (56,'Eritrea');
INSERT INTO Country (Id, Name) VALUES (57,'Estonia');
INSERT INTO Country (Id, Name) VALUES (58,'Ethiopia');
INSERT INTO Country (Id, Name) VALUES (59,'Fiji');
INSERT INTO Country (Id, Name) VALUES (60,'Finland');
INSERT INTO Country (Id, Name) VALUES (61,'France');
INSERT INTO Country (Id, Name) VALUES (62,'Gabon');
INSERT INTO Country (Id, Name) VALUES (63,'Gambia, The');
INSERT INTO Country (Id, Name) VALUES (64,'Georgia');
INSERT INTO Country (Id, Name) VALUES (65,'Germany');
INSERT INTO Country (Id, Name) VALUES (66,'Ghana');
INSERT INTO Country (Id, Name) VALUES (67,'Greece');
INSERT INTO Country (Id, Name) VALUES (68,'Grenada');
INSERT INTO Country (Id, Name) VALUES (69,'Guatemala');
INSERT INTO Country (Id, Name) VALUES (70,'Guinea');
INSERT INTO Country (Id, Name) VALUES (71,'Guinea-Bissau');
INSERT INTO Country (Id, Name) VALUES (72,'Guyana');
INSERT INTO Country (Id, Name) VALUES (73,'Haiti');
INSERT INTO Country (Id, Name) VALUES (74,'Honduras');
INSERT INTO Country (Id, Name) VALUES (75,'Hungary');
INSERT INTO Country (Id, Name) VALUES (76,'Iceland');
INSERT INTO Country (Id, Name) VALUES (77,'India');
INSERT INTO Country (Id, Name) VALUES (78,'Indonesia');
INSERT INTO Country (Id, Name) VALUES (79,'Iran');
INSERT INTO Country (Id, Name) VALUES (80,'Iraq');
INSERT INTO Country (Id, Name) VALUES (81,'Ireland');
INSERT INTO Country (Id, Name) VALUES (82,'Israel');
INSERT INTO Country (Id, Name) VALUES (83,'Italy');
INSERT INTO Country (Id, Name) VALUES (84,'Jamaica');
INSERT INTO Country (Id, Name) VALUES (85,'Japan');
INSERT INTO Country (Id, Name) VALUES (86,'Jordan');
INSERT INTO Country (Id, Name) VALUES (87,'Kazakhstan');
INSERT INTO Country (Id, Name) VALUES (88,'Kenya');
INSERT INTO Country (Id, Name) VALUES (89,'Kiribati');
INSERT INTO Country (Id, Name) VALUES (90,'Korea, North');
INSERT INTO Country (Id, Name) VALUES (91,'Korea, South');
INSERT INTO Country (Id, Name) VALUES (92,'Kuwait');
INSERT INTO Country (Id, Name) VALUES (93,'Kyrgyzstan');
INSERT INTO Country (Id, Name) VALUES (94,'Laos');
INSERT INTO Country (Id, Name) VALUES (95,'Latvia');
INSERT INTO Country (Id, Name) VALUES (96,'Lebanon');
INSERT INTO Country (Id, Name) VALUES (97,'Lesotho');
INSERT INTO Country (Id, Name) VALUES (98,'Liberia');
INSERT INTO Country (Id, Name) VALUES (99,'Libya');
INSERT INTO Country (Id, Name) VALUES (100,'Liechtenstein');
INSERT INTO Country (Id, Name) VALUES (101,'Lithuania');
INSERT INTO Country (Id, Name) VALUES (102,'Luxembourg');
INSERT INTO Country (Id, Name) VALUES (103,'Macedonia, Former Yugoslav Republic of');
INSERT INTO Country (Id, Name) VALUES (104,'Madagascar');
INSERT INTO Country (Id, Name) VALUES (105,'Malawi');
INSERT INTO Country (Id, Name) VALUES (106,'Malaysia');
INSERT INTO Country (Id, Name) VALUES (107,'Maldives');
INSERT INTO Country (Id, Name) VALUES (108,'Mali');
INSERT INTO Country (Id, Name) VALUES (109,'Malta');
INSERT INTO Country (Id, Name) VALUES (110,'Marshall Islands');
INSERT INTO Country (Id, Name) VALUES (111,'Mauritania');
INSERT INTO Country (Id, Name) VALUES (112,'Mauritius');
INSERT INTO Country (Id, Name) VALUES (113,'Mexico');
INSERT INTO Country (Id, Name) VALUES (114,'Micronesia, Federated States of');
INSERT INTO Country (Id, Name) VALUES (115,'Moldova');
INSERT INTO Country (Id, Name) VALUES (116,'Monaco');
INSERT INTO Country (Id, Name) VALUES (117,'Mongolia');
INSERT INTO Country (Id, Name) VALUES (118,'Morocco');
INSERT INTO Country (Id, Name) VALUES (119,'Mozambique');
INSERT INTO Country (Id, Name) VALUES (120,'Myanmar');
INSERT INTO Country (Id, Name) VALUES (121,'Namibia');
INSERT INTO Country (Id, Name) VALUES (122,'Nauru');
INSERT INTO Country (Id, Name) VALUES (123,'Nepal');
INSERT INTO Country (Id, Name) VALUES (124,'Netherlands');
INSERT INTO Country (Id, Name) VALUES (125,'New Zealand');
INSERT INTO Country (Id, Name) VALUES (126,'Nicaragua');
INSERT INTO Country (Id, Name) VALUES (127,'Niger');
INSERT INTO Country (Id, Name) VALUES (128,'Nigeria');
INSERT INTO Country (Id, Name) VALUES (129,'Norway');
INSERT INTO Country (Id, Name) VALUES (130,'Oman');
INSERT INTO Country (Id, Name) VALUES (131,'Pakistan');
INSERT INTO Country (Id, Name) VALUES (132,'Palau');
INSERT INTO Country (Id, Name) VALUES (133,'Panama');
INSERT INTO Country (Id, Name) VALUES (134,'Papua New Guinea');
INSERT INTO Country (Id, Name) VALUES (135,'Paraguay');
INSERT INTO Country (Id, Name) VALUES (136,'Peru');
INSERT INTO Country (Id, Name) VALUES (137,'Philippines');
INSERT INTO Country (Id, Name) VALUES (138,'Poland');
INSERT INTO Country (Id, Name) VALUES (139,'Portugal');
INSERT INTO Country (Id, Name) VALUES (140,'Qatar');
INSERT INTO Country (Id, Name) VALUES (141,'Romania');
INSERT INTO Country (Id, Name) VALUES (142,'Russia');
INSERT INTO Country (Id, Name) VALUES (143,'Rwanda');
INSERT INTO Country (Id, Name) VALUES (144,'Saint Kitts and Nevis');
INSERT INTO Country (Id, Name) VALUES (145,'Saint Lucia');
INSERT INTO Country (Id, Name) VALUES (146,'Saint Vincent and The Grenadines');
INSERT INTO Country (Id, Name) VALUES (147,'Samoa');
INSERT INTO Country (Id, Name) VALUES (148,'San Marino');
INSERT INTO Country (Id, Name) VALUES (149,'Sao Tome and Principe');
INSERT INTO Country (Id, Name) VALUES (150,'Saudi Arabia');
INSERT INTO Country (Id, Name) VALUES (151,'Senegal');
INSERT INTO Country (Id, Name) VALUES (152,'Serbia and Montenegro');
INSERT INTO Country (Id, Name) VALUES (153,'Seychelles');
INSERT INTO Country (Id, Name) VALUES (154,'Sierra Leone');
INSERT INTO Country (Id, Name) VALUES (155,'Singapore');
INSERT INTO Country (Id, Name) VALUES (156,'Slovakia');
INSERT INTO Country (Id, Name) VALUES (157,'Slovenia');
INSERT INTO Country (Id, Name) VALUES (158,'Solomon Islands');
INSERT INTO Country (Id, Name) VALUES (159,'Somalia');
INSERT INTO Country (Id, Name) VALUES (160,'South Africa');
INSERT INTO Country (Id, Name) VALUES (161,'Spain');
INSERT INTO Country (Id, Name) VALUES (162,'Sri Lanka');
INSERT INTO Country (Id, Name) VALUES (163,'Sudan');
INSERT INTO Country (Id, Name) VALUES (164,'Suriname');
INSERT INTO Country (Id, Name) VALUES (165,'Swaziland');
INSERT INTO Country (Id, Name) VALUES (166,'Sweden');
INSERT INTO Country (Id, Name) VALUES (167,'Switzerland');
INSERT INTO Country (Id, Name) VALUES (168,'Syria');
INSERT INTO Country (Id, Name) VALUES (169,'Taiwan');
INSERT INTO Country (Id, Name) VALUES (170,'Tajikistan');
INSERT INTO Country (Id, Name) VALUES (171,'Tanzania');
INSERT INTO Country (Id, Name) VALUES (172,'Thailand');
INSERT INTO Country (Id, Name) VALUES (173,'Togo');
INSERT INTO Country (Id, Name) VALUES (174,'Tonga');
INSERT INTO Country (Id, Name) VALUES (175,'Trinidad and Tobago');
INSERT INTO Country (Id, Name) VALUES (176,'Tunisia');
INSERT INTO Country (Id, Name) VALUES (177,'Turkey');
INSERT INTO Country (Id, Name) VALUES (178,'Turkmenistan');
INSERT INTO Country (Id, Name) VALUES (179,'Tuvalu');
INSERT INTO Country (Id, Name) VALUES (180,'Uganda');
INSERT INTO Country (Id, Name) VALUES (181,'Ukraine');
INSERT INTO Country (Id, Name) VALUES (182,'United Arab Emirates');
INSERT INTO Country (Id, Name) VALUES (183,'United Kingdom');
INSERT INTO Country (Id, Name) VALUES (184,'United States');
INSERT INTO Country (Id, Name) VALUES (185,'Uruguay');
INSERT INTO Country (Id, Name) VALUES (186,'Uzbekistan');
INSERT INTO Country (Id, Name) VALUES (187,'Vanuatu');
INSERT INTO Country (Id, Name) VALUES (188,'Vatican City');
INSERT INTO Country (Id, Name) VALUES (189,'Venezuela');
INSERT INTO Country (Id, Name) VALUES (190,'Vietnam');
INSERT INTO Country (Id, Name) VALUES (191,'Western Sahara');
INSERT INTO Country (Id, Name) VALUES (192,'Yemen');
INSERT INTO Country (Id, Name) VALUES (193,'Zambia');
INSERT INTO Country (Id, Name) VALUES (194,'Zimbabwe');
INSERT INTO Country (Id, Name) VALUES (207,'Hong Kong');
INSERT INTO Country (Id, Name) VALUES (208,'Puerto Rico');
-- SQLSERVER SET IDENTITY_INSERT Country OFF;

UPDATE Country set SequenceNumber=10;

-- SQLSERVER GO